### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by MBratkowski**
- Optimize layouts structures
- Extract values from layout files to resources files.

### CODE REVIEW

**Comment by MBratkowski** [comment]
@hypeapps You have to check a pull request with update resources.

**Comment by hypeapps** [comment]
@MBratkowski I will check the changes soon. Thank you for awesome job!

**Comment by hypeapps** [comment]
@MBratkowski I saw the changes. Changing variables names and deleting empty lines and reorganize image icons was good idea but there's couple problems with layouts. While you reorganizing layouts you forget about few parameters like textSize, gravity etc. Layout doesn't work properly on smaller screen sizes.

**Comment by MBratkowski** [comment]
@hypeapps Thanks for answer :)!

Parameters like 'textSize' must be extract to the dimens.xml file. And you can have multiple dimens.xml files to the support different screens (like- values-mdpi, support screens with mdpi size). This is a one of type good practice for developing android applications.

Layout files must be simple, if don't then application used more resources to rendering frame, and this affect to the usage battery.

Maybe we could collaborate with simple application to the task management like Trello? What do you think about this idea?

**Comment by hypeapps** [comment]
@MBratkowski Of course we can. My account on trello @przemek204

**Pull request closed without merging**
